[package]
name = "hang_man_game"
version = "0.1.0"
authors = ["Yeshwanth Bommareddy <40725768+yeshwanth32@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3"
crossterm = "0.11"